### ISSUE TITLE
player cant move without holding space in spectator mode

### ISSUE THREAD

**Issue by ALor79** [Chryscorelab/HardcoreLife#10]
hey we recently one of our players died and it was her last life but she died to lag so we set her life back to 1 but she still cant move. is there any way to run the command "PlayerLife.clearLivesData();" for her?

**Comment by drewburr** [comment]
Thanks for opening this up! There is not a currently supported process for increasing life after it hits 0, however, this is something we need to fix. A workaround would be to have the player log out, then delete the player's data file from under the `world` folder.

I'll see if we can get a patch in place that would fix this without requiring you to delete files. Ideally, we'd reset the player's speed settings when `/setlives` is used to change the life value from 0.

**Comment by drewburr** [comment]
@ALor79 this has been fixed in [v2.1.0](https://github.com/Chryscorelab/HardcoreLife/releases/tag/2.1.0) and is fully compatible with 2.0.0. Just install the new version and you'll be good to go!

If any players are actively stuck with movement speed issues, set their lives to 0, then increase it again. This will trigger the process of respawning the player. Also note that the player will die during this process, so a TP may be necessary. Let me know if you have any issues!
